export { default as Login } from './auth/Login.vue';
export { default as Logout } from './auth/Logout.vue';
export { default as Cars } from './cars/Cars.vue';
export { default as Dashboard } from './dashboard/Dashboard.vue';
export { default as CarRequest } from './cars/Request.vue';
export { default as ManagerResponse } from './cars/ManagerResponse.vue';
export { default as CarVoting } from './carvoting/Voting.vue';
export { default as CarFinalApproval } from './carInventory/FinalApproval.vue';
export { default as CarsAndEmployees } from './carInventory/CarsAndEmployees.vue';
